Füge Überprüfung veralteter Abhängigkeiten vor dem Audit-Schritt hinzu

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,7 +40,9 @@ jobs:
         run: npm run build
 
       - name: Audit (non-blocking)
-        run: npm audit || true  # ignore failures
+        run: |
+            npm list --outdated    
+            npm audit || true  # ignore failures
 
   publish-npm:
     # publish only if we are on our own repo, event was 'release' (a tag was created) and the tag starts with "v" (aka version tag)
