update dependencies and build

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -35,11 +35,23 @@ jobs:
       - name: npm install and build
         run: |
           npm install
-          npm run build --if-present
           npm test
-        env:
-          CI: true
+      - name: Lint the project
+        run: npm run lint
 
+      - name: Build the project
+        run: npm run build
+
+      - name: List, audit, fix outdated dependencies and build again
+        run: |
+          npm list --outdated
+          npm audit || true  # ignore failures
+          npm audit fix || true
+          npm list --outdated
+          npm run build
+
+      - name: npm install and build
+        run: npm test
   publish-npm:
     # publish only if we are on our own repo, event was 'release' (a tag was created) and the tag starts with "v" (aka version tag)
     if: github.repository == 'california444/homebridge-doorbell-telegram-photo' && github.event_name == 'release'
